# Dependencies
markdown:         rdiscount
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Seonho Oh
tagline:          'The personal blog'
description:      'The personal blog of Seonho Oh'
url:              http://seonho.github.io

author:
  name:           'Seonho Oh'
  url:            https://twitter.com/serioush

paginate:         1

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/seonho

# This is the list of pages to include in the header of the website.
pages_list: {'About':'/about', 'Archive':'/archive','Feed':'/atom.xml'}

# Allow URL redirects:
# * https://help.github.com/articles/redirects-on-github-pages
gems:
  - jekyll-redirect-from
