# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Seonho Oh
#tagline:          'The personal blog'
description:      'Think different. Being positive.'

author:
  name:           'Seonho Oh'
  twitter:        seriousoh
  github:         seonho
  linkedin:       seonho

paginate:         1

# Custom vars
version:          1.0.0

redcarpet:
    extensions:
      - no_intra_emphasis
      - fenced_code_blocks
      - tables
      - strikethrough
      - superscript
      - autolink
      - hard_wrap

# Allow URL redirects:
# * https://help.github.com/articles/redirects-on-github-pages
gems:
  - jekyll-redirect-from

exclude:
  - Rakefile
